version: 2
machine:
  node:
    version: stable
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          - POSTGRES_USER=jubilant
          - POSTGRES_PASSWORD=jubilant
          - POSTGRES_DB=jubilant_test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1a-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1a-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1a-dependencies-{{ checksum "package.json" }}

      - run: make test-full

